version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

references:
  default_image: &default_image
    docker:
        - image: 'cimg/ruby:2.7'

  test_suite: &test_suite
    run:
      name: Run test suite
      command: bundle exec rake spec

  lint: &lint
    run:
      name: Code Checks
      command: bundle exec rubocop --parallel

  bundle: &bundle
    run:
      name: bundle install dependencies
      command: bundle install

  persist_reports: &persist_reports
    persist_to_workspace:
      root: .
      paths:
        - coverage/coverage.json
        - coverage/sonarcube-report.xml

  mount_reports: &mount_reports
    attach_workspace:
      at: .

jobs:
  lint:
    <<: *default_image
    steps:
      - checkout
      - <<: *bundle
      - <<: *lint

  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: 'cimg/ruby:<< parameters.ruby-version >>'
    steps:
      - checkout
      - <<: *bundle
      - <<: *mount_reports
      - <<: *test_suite
      - when:
          condition:
            and:
              - equal: [ '2.7', << parameters.ruby-version >> ]
          steps:
            - <<: *persist_reports
            - store_artifacts:
                path: coverage

  report:
    <<: *default_image
    steps:
      - checkout
      - <<: *mount_reports
      - sonarcloud/scan

workflows:
  build_and_test:
    jobs:
      - lint
      - test:
          requires:
            - lint
          matrix:
            parameters:
              ruby-version: ['2.7', '3.0', '3.1']
      - report:
          context: SonarCloud
          requires:
            - lint
            - test